
#Common Configs for KitchenKarrot
["Canned Food Settings"]
	#Whether or not an empty can entity spawns everytime player finished eating a canned food.
	"Spawn Empty Can Entity" = true
	#The maximum time in seconds an empty can entity can live.
	#10 by default, -1 to prevent disappearing.
	"Can Entity Lifetime" = 10

["Villager Trade Settings"]
	#Will butcher villager sell salt at level 1.
	"Butcher Sell Salt" = true
	#Will butcher villager sell oil at level 1.
	"Butcher Sell Oil" = true
	#Will farmer villager buy gem carrot at level 3.
	"Farmer Buy Gem Carrot" = true

["Cocktail Settings"]
	#Unknown cocktail gives a random effect in the game except following.
	"Unknown Cocktail Effects Blacklist" = ["minecraft:instant_health", "minecraft:instant_damage", "minecraft:bad_omen", "minecraft:hero_of_the_village"]
	#Turn the blacklist above into a whitelist.Only the given effects will be applied.
	#False by default.
	"Whitelist Mode" = false

