#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Dec 04 22:21:46 CST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=ComplementaryShaders_v4.6.zip
enableShaders=false
