#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Oct 29 03:40:23 CST 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=ComplementaryShaders_v4.6.zip
enableShaders=false
